/*
 handle.timer && (handle.timer = setInterval(function(){
    handle._fix.call(mag, handle.e);
   }, 1));*/
var Preload=function(){var m=function(){},l=function(c){return Object.prototype.toString.call(c).match(/\w+/g)[1].toLowerCase()},b=function(c){if("string"!==typeof c)throw"param str is not a string";return c.replace(/^[\s\u00A0]+|[\s\u00A0]+$/g,"")},d=function(c,g,b){c||(c="#null");"string"===typeof c&&(this.url=c||"#null");g||(g=m);"function"===typeof g&&(this.success=g);b||(b=m);"function"===typeof g&&(this.error=b);this.times=0};d.prototype={valid:function(){this.url=b(this.url);return"string"===
typeof this.url&&"#null"!==this.url&&""!==this.url}};var f=function(c){return"string"===l(c)?new d(c):"object"===l(c)?new d(c.url,c.success,c.error):new d},r=function(c){var g=document.createElement("img");g.style.cssText="position:absolute; top:-9999px; left:-9999px;";var b=function(){"function"===typeof c.success&&c.success.call(this,c);this.onload=this.onerror=this.onabort=m;document.body.removeChild(this)},d=function(){"function"===typeof c.error&&c.error.call(this,c);this.onload=this.onerror=
this.onabort=m;document.body.removeChild(this)};g.src=c.url;document.body.appendChild(g);g.complete?b.call(g):(g.onload=b,g.onerror=g.onabort=d)},h=function(c,g){for(var b=0,d=c.length,a=-1;b<d;b++)if(c[b]===g){a=b;break}return a},n=function(c){var g=this._={};g.status=1;g.queue=[];g.thread=[];g.retry=[];g.fail=[];g.done=[];g.cfg={thread:4,retry:1};if(c){var b=parseInt(c.thread);b&&0<b&&(g.cfg.thread=b);(b=parseInt(c.retry))&&0<=b&&(g.cfg.retry=b)}var d=function(){switch(g.status){case 5:g.queue.splice(0,
g.queue.length);g.retry.splice(0,g.retry.length);break;case 1:case 2:case 3:if(g.thread.length<=g.cfg.thread){var a;g.retry.length&&[].push.apply(g.queue,g.retry.splice(0,g.retry.length));(a=g.queue.length&&g.queue.splice(0,1)[0])?(g.thread.push(a),r(a)):g.thread.length||(g.status=3)}}},a=function(a,k){var e=a.success,c=a.error;a.success=function(){e.apply(this,arguments);var c=h(k.thread,a);k.thread.splice(c,1);k.done.push(a);d()};a.error=function(){c.apply(this,arguments);var e=h(k.thread,a);k.thread.splice(e,
1);a.times<k.cfg.retry?(k.retry.push(a),a.times++):k.fail.push(a);d()};return a};g.ctrl={start:function(){g.status=2;for(var a=g.cfg.thread-g.thread.length;a--&&g.queue.length;)d()},pause:function(){g.status=4},stop:function(){g.status=5}};this.load=function(e){var k;if("array"===l(e))for(k=0;k<e.length;k++){var c=f(e[k]);c.valid()&&(a(c,g),this._.queue.push(c))}else c=f(e),c.valid()&&(a(c,g),this._.queue.push(c));this._.ctrl.start();return this}};n.prototype={isLoaded:function(c){c=b(c);for(var g=
!1,d=this._.done,f=0,a=d.length;f<a;f++)if(b(d[f].url)===c){g=!0;break}return g},isLoading:function(c){for(var b=!1,d=this._.thread,f=0,a=d.length;f<a;f++)if(d[f].url===c){b=!0;break}return b},isFailed:function(c){for(var b=!1,d=this._.fail,f=0,a=d.length;f<a;f++)if(d[f].url===c){b=!0;break}return b}};return n}.call(this),CSSRuleOperator=function(){var m=function(b){return b.replace(/(^|\s+)[A-Z]+/g,function(b){return b.toLowerCase()})},l=function(b){b||(b=document.createElement("style"),b.type="text/css",
document.getElementsByTagName("head")[0].appendChild(b));this.sheet=b.sheet||b.styleSheet||b;this.rules=this.sheet.cssRules||this.sheet.rules};l.prototype={get:function(b){var d=parseInt(b);if("number"===typeof d&&-1<d&&d<this.rules.length)var f=this.rules[d];else if("string"===typeof b){b=m(b);var l;this.each(function(d,n){l=m(n.selectorText);if(l===b)return f=this.rules[d],!0})}return f?{selectorText:f.selectorText,cssText:f.cssText||f.selectorText+"{"+f.style.cssText+"}",style:this.split(f.cssText||
f.style.cssText)}:f},set:function(b,d,f,l){var h={selectorText:b,style:{}};if(l){h=this.get(b)||h;try{this.del(h.selectorText)}catch(c){}}"string"===typeof d&&(d=this.split(d));b=h.style;for(var m in d)b[m]=d[m];f=f||this.rules.length;f=f>=this.rules.length||0>f?this.rules.length:f;this.sheet.insertRule?this.sheet.insertRule(this.toCssText(h.selectorText,h.style),f):(f=f>this.rules.length?-1:f,this.sheet.addRule(h.selectorText,this.toRuleStr(h.style),f))},del:function(b){if(this.sheet.removeRule)return this.sheet.removeRule(b),
!0;var d=parseInt(b);if("number"===typeof d&&-1<d&&d<this.rules.length)this.sheet.deleteRule(d);else if("string"===typeof b){b=m(b);var f;this.each(function(d,h){f=m(h.selectorText);if(f===b)return this.sheet.deleteRule(d),!0})}},exist:function(b){b=m(b);var d,f;this.each(function(l,h){d=m(h.selectorText);if(d===b)return f=!0});return f},each:function(b){for(var d=0,f=this.rules.length,l;d<f&&!(l=b.call(this,d,this.rules[d]));d++);return this},split:function(b){var d={};b.replace(/([-a-zA-Z]+)\s*\:\s*([^;]+)/g,
function(b,l,h){d[l.toLowerCase()]=h});return d},toRuleStr:function(b){var d=[],f;for(f in b)d.push(f,":",b[f],";");return d.join("")},toCssText:function(b,d){var f=[b,"{"];f.push(this.toRuleStr(d));f.push("}");return f.join("")}};return l}.call(this),Magnifier=function(m,l,b){var d=function(){},f=function(){var a=l.createElement("style");a.type="text/css";l.getElementsByTagName("head")[0].appendChild(a);this.rule=new c.Rule(a)},r=function(){var a=["position:absolute; top:-",9999,"px; left:-",9999,
"px;"];if(c.browser.msie&&9>c.browser.version)a.push("background-color:",this.config.layer.bgColor,"\\9; filter:alpha(opacity\x3d",100*this.config.layer.alpha,")\\9;");else{var e=c.color.toRGB(this.config.layer.bgColor);a.push("background-color:rgba(",e.R,",",e.G,",",e.B,",",this.config.layer.alpha,");")}this.config.layer.bgImage&&(a.push("background-image:url('",this.config.layer.bgImage,"');"),c.browser.msie?a.push("filter:alpha(opacity\x3d",100*this.config.layer.alpha,");"):a.push("opacity:",this.config.layer.alpha,
";"));a.push("cursor:",this.config.layer.cursor,"; diplay:block; width:90px; height:60px;");this.rule.set(".magnifier_layer_"+this.uuid,a.join(""));a=["position:absolute; overflow:hidden; top:-",9999,"px; left:-",9999,"px;"];a.push("width:",this.config.detail.width,"px;");a.push("height:",this.config.detail.height,"px;");a.push("border:",this.config.detail.borderWidth,"px ",this.config.detail.borderStyle," ",this.config.detail.borderColor,";");a.push("background-color:",this.config.detail.bgColor,
";");a.push("opacity:",this.config.detail.alpha,"; filter:alpha(opacity\x3d",100*this.config.detail.alpha,");");a.push("z-index:1000;");this.rule.set(".magnifier_detail_"+this.uuid,a.join(""));a=["display:block; overflow:hidden; position:absolute; top:50%; left:50%;"];this.rule.set(".magnifier_loading_"+this.uuid,a.join(""));a=["display:block; overflow:hidden; position:absolute; top:50%; left:50%;"];this.rule.set(".magnifier_detailLayer_"+this.uuid,a.join(""));a=["display:block; margin:0 auto; position:relative;"];
this.rule.set(".magnifier_detailImg_"+this.uuid,a.join(""))};b=new Abstract({show:function(a,e,c){},hide:function(){},changeTarget:function(a){},dispose:function(){},turn:function(a){},showLayer:function(){},hideLayer:function(){},showDetailImg:function(){},hideDetailImg:function(){},showLoading:function(){},hideLoading:function(){},setDetailImageSrc:function(a){},changeDetail:function(a,e,c){}});var h=new Clazz(b,{inherit:Component,config:{layer:{bgColor:"#000",alpha:.3,bgImage:"",opacity:1,cursor:"move"},
detail:{width:450,height:300,borderColor:"#ccc",borderWidth:1,borderStyle:"solid",bgColor:"#fff",opacity:1,offsetX:10,offsetY:0},target:null,detailImg:"",loading:""}},function(a){if(this===m)return new h(a);var e=this;this.setConfig(a);if(!this.config.target)throw"target is required";this.uuid=(new Date).valueOf()+""+c.random(0,1E3);f.call(this);r.call(this);this.loader=new c.Preload({thread:2,retry:1});this.__init();this.loader.load({url:this.config.loading,success:function(){e.elems.loading.src=
this.src;g.call(this,e.elems.loading)}})});h.readyState=!1;h.ready=function(a){"function"===typeof a&&(h.readyState?a():n.readyHandle.push(a))};var n=h._={};n.readyHandle=[];var c=h.tools={};c.random=function(a,e){return Math.floor((e-a)*Math.random()+a)};c.type=function(a){var e="undefined"===typeof a?"undefined":null===a?"null":Object.prototype.toString.call(a).match(/\w+/g)[1].toLowerCase();"number"===e&&isNaN(a)&&(e="nan");return e};c.search=function(a,e){for(var c=0,b=a.length,d=-1;c<b;c++)if(a[c]===
e){d=c;break}return d};c.color={RESULT:{RGB:"rgb",HEX:"hex",UNKNOWN:null},valid:function(a){var e=c.type(a),b=this.RESULT.UNKNOWN;"object"===e&&"R"in a&&0<=+a.R&&255>=+a.R&&"G"in a&&0<=+a.G&&255>=+a.G&&"B"in a&&0<=+a.B&&255>=+a.B?b=this.RESULT.RGB:"string"===e&&/^#?([0-9a-f]{3}|[0-9a-f]{6})$/i.test(a)&&(b=this.RESULT.HEX);return b},toHEX:function(a){var e="#";this.valid(a)===this.RESULT.RGB?(e+=parseInt(a.R).toString(16),e+=parseInt(a.G).toString(16),e+=parseInt(a.B).toString(16)):e="#000";return e},
toRGB:function(a){var e={R:0,G:0,B:0};this.valid(a)===this.RESULT.HEX&&(a=a.replace(/#/,"").toLowerCase(),3===a.length&&(a=a.replace(/([0-9a-f])/g,"$1$1")),a=a.match(/[0-9a-f]{2}/g),e.R=parseInt(a[0],16),e.G=parseInt(a[1],16),e.B=parseInt(a[2],16));return e}};c.getScript=function(a,e,c){var b=l.getElementsByTagName("head")[0],k=l.createElement("script");k.type="text/javascript";k.defer=!0;k.aysnc=!0;var g=function(){k.onreadystatechange=d;k.onload=d;k.onerror=d};k.src=a;b.appendChild(k);k.complete||
k.loaded||"complete"===k.readyState||"loaded"===k.readyState?g():(k.onreadystatechange=function(a){if("complete"===k.readyState||"loaded"===k.readyState)e.call(k,a||m.event),g()},k.onload=function(a){(e||d).call(k,a||m.event);g()},k.onerror=function(a){(c||d).call(k,a||m.event);g()})};c.require=function(){var a=[].slice.call(arguments),e=d;"function"===typeof a[a.length-1]&&(e=a.pop());if(a.length)for(var b=Array(a.length+1).join(0).split(""),g=0;g<a.length;g++)"string"===typeof a[g]&&c.getScript(a[g],
function(a){return function(){b[a]="1";-1===c.search(b,"0")&&e()}}(g));else e()};n.init=function(){for(var a;a=n.readyHandle.shift();)a()};c.pageXY=function(a){a=a.getBoundingClientRect();var e=m.scrollTop||l.documentElement&&l.documentElement.scrollTop||l.body.scrollTop||0,c=m.scrollLeft||l.documentElement&&l.documentElement.scrollLeft||l.body.scrollLeft||0,b=(l.documentElement||l.getElementsByTagName("html")[0]).getBoundingClientRect();b={left:0>b.left?0:b.left,top:0>b.top?0:b.top};/msie\s*6/i.test(m.navigator.appVersion)&&
(b={left:b.left+2,top:b.top+2});return{left:a.left+c-b.left,top:a.top+e-b.top}};var g=function(a,e,b){a.width=this.width;a.height=this.height;var k=c.type(e),g=c.type(b);e="number"===k?-e+"px":"undefined"===k?-this.width/2+"px":e;b="number"===g?-b+"px":"undefined"===g?-this.height/2+"px":b;a.style.cssText+=";margin-top:"+b+"; margin-left:"+e+";";a.src=this.src},q={e:{clientX:0,clientY:0},_fix:function(a){if(this.loader.isLoaded(this.config.detailImg)){var e=this.elems.target,b=this.elems.layer,g=
this.elems.detailLayer,d=e.getBoundingClientRect(),f=parseInt(e.currentStyle?e.currentStyle.borderTopWidth:l.defaultView.getComputedStyle(e,null).borderTopWidth);f="nan"===c.type(f)?2:f;var h=a.clientX-d.left-f;d=a.clientY-d.top-f;h>e.clientWidth-b.clientWidth/2?(h="auto",a=0):(h=h>b.clientWidth/2?h-b.clientWidth/2:0,a="auto");d>e.clientHeight-b.clientHeight/2?(d="auto",f=0):(d=d>b.clientHeight/2?d-b.clientHeight/2:0,f="auto");b.style.cssText+=";left:"+("auto"===h?h:h+"px")+"; top:"+("auto"===d?d:
d+"px")+"; right:"+("auto"===a?a:a+"px")+"; bottom:"+("auto"===f?f:f+"px")+";";e=e.clientWidth/g.clientWidth;g.style.cssText+=";left:"+("auto"===h?h:-h/e+"px")+"; top:"+("auto"===d?d:-d/e+"px")+"; right:"+("auto"===a?a:-a/e+"px")+"; bottom:"+("auto"===f?f:-f/e+"px")+";"}},timer:0,_enter:function(a,e,b){if(e.STATUS===p.OFF)e.hide();else if(a=b.detailImg)e.loader.isLoaded(a)?e.show(a):e.loader.isLoading()||(e.showLoading(),e.show(a))},_leave:function(a,e){e.hideLayer();e.hide()},_move:function(a,e){e.STATUS===
p.OFF?e.hide():q._fix.call(e,a)}},p=h.SWITCH_STATUS={OFF:0,ON:1};h.extend({showLayer:function(){},hideLayer:function(){this.elems.layer.style.cssText+=";left:-9999px; top:-9999px;"},showDetailImg:function(){this.elems.detailLayer.style.cssText+=";left:0; top:0;"},hideDetailImg:function(){this.elems.detailLayer.style.cssText+=";left:-9999px; top:-9999px;"},showLoading:function(){this.elems.loading.style.cssText+=";left:50%; top:50%;";this.fire("loading")},hideLoading:function(){this.elems.loading.style.cssText+=
";left:-9999px; top:-9999px;";this.fire("loaded")},setDetailImageSrc:function(a){"string"===c.type(a)&&(this.hideDetailImg(),this.config.detailImg=a,this.fire("setDetailImageSrc",{src:a}));return this},changeDetail:function(a,e,b){var d=this;if(a=a||this.config.detailImg){this.showLoading();this.hideDetailImg();this.config.detailImg=a;var f=c.type(e),k=c.type(b);e="number"===f?e:"undefined"===f?"auto":0;b="number"===k?b:k?"auto":0;this.loader.load({url:a,success:function(){var a=d.elems.layer,c=d.elems.detail,
f=d.elems.target,k=d.elems.detailLayer,h=d.elems.detailImg;g.call(this,h,e,b);f.clientWidth*this.height>f.clientHeight*this.width?(k.style.height=this.height+"px",k.style.width=this.height*f.clientWidth/f.clientHeight+"px",h.style.marginTop="0px"):(k.style.width=this.width+"px",k.style.height=this.width*f.clientHeight/f.clientWidth+"px",h.style.marginTop=Math.abs((k.clientHeight-this.height)/2)+"px");a.style.cssText+=";width:"+f.clientWidth*c.clientWidth/k.clientWidth+"px; height:"+f.clientHeight*
c.clientHeight/k.clientHeight+"px;";d.showDetailImg();d.hideLoading()}});this.fire("changeDetail",{src:a,x:e,y:b});return this}},show:function(a,b,d){if(this.STATUS===p.OFF)this.hide();else{"string"===c.type(a)&&this.changeDetail(a);var e=c.pageXY(this.elems.target);b="number"===c.type(b)?b:this.config.detail.offsetX;d="number"===c.type(d)?d:this.config.detail.offsetY;this.elems.detail.style.cssText+=";left:"+(e.left+this.elems.target.offsetWidth+b)+"px; top:"+(e.top+d)+"px;";this.fire("show",{src:a,
offsetX:b,offsetY:d});return this}},hide:function(){this.elems.detail.style.cssText+=";left:-9999px; top:-9999px;";this.fire("hide");return this},__init:function(){this.fire("beforeInit");var a=this.elems;a.target=this.config.target;/relative|absolute/i.test(a.target.style.position)||(a.target.style.cssText+=";position:relative");a.target.style.cssText+="; overflow:hidden;";var b=l.createElement("div");b.className="magnifier_detail_"+this.uuid;b.style.cssText+=";left:-9999px; top:-9999px;";l.body.appendChild(b);
a.detail=b;var c=l.createElement("img");c.className="magnifier_loading_"+this.uuid;c.style.cssText+=";z-index:10;";b.appendChild(c);a.loading=c;c=l.createElement("div");c.className="magnifier_detailLayer_"+this.uuid;c.style.cssText+=";z-index:100;";b.appendChild(c);a.detailLayer=c;b=l.createElement("img");b.className="magnifier_detailImg_"+this.uuid;c.appendChild(b);a.detailImg=b;b=l.createElement("div");b.className="magnifier_layer_"+this.uuid;b.style.cssText+=";left:-9999px; top:-9999px;";a.target.appendChild(b);
a.layer=b;h.bindEvt(a.target,"mousemove",function(){var a=this;return function(b){q._move.call(b.target||b.srcElement,b,a)}}.call(this));h.bindEvt(a.target,"mouseenter",function(){var a=this;return function(b){q._enter.call(b.target||b.srcElement,b,a,a.config)}}.call(this));h.bindEvt(a.target,"mouseleave",function(){var a=this;return function(b){q._leave.call(b.target||b.srcElement,b,a)}}.call(this));try{delete this.init}catch(t){}this.fire("init")},changeTarget:function(a){var b=this.elems.target;
this.elems.target=this.config.target=a;this.fire("changeTarget",{target:a,prevTarget:b});return this},dispose:function(){return this},turn:function(a){a="undefined"===typeof a?"ON":(a+"").toUpperCase()in p?(a+"").toUpperCase():a?"ON":"OFF";this.STATUS=p[a];this.fire("turn",{status:a});return this}});b=function(){var a=[],b;for(b in this)m[this[b].namespace]||a.push(this[b].src);return a}.call({0:{name:"preload",namespace:"Preload",src:"/script/magnifier/preload.js"},1:{name:"CSSRuleOperator",namespace:"CSSRuleOperator",
src:"/script/magnifier/cssrule.js"}});b.push(function(){jQuery(function(){h.readyState=!0;c.browser=jQuery.browser;h.bindEvt=function(a,b,c){jQuery(a).bind(b,c)};h.unbindEvt=function(a,b,c){jQuery(a).unbind(b,c)};c.Preload=m.Preload;c.Rule=m.CSSRuleOperator;n.init()})});c.require.apply(this,b);return h}.call(this,window,document);